### ISSUE TITLE
Unable to update provides database due to expired TLS certificate and non-listening subdomain.

### ISSUE THREAD

**Issue by jbirch** [rosorio/pkg-provides#10]
The certificate for `osorio.me` has expired, and nothing seems to listen on `pkg-provides.osorio.me`, which prevents the update command working without `PROVIDES_SRV`.

```
# pkg provides -u
fetchStatURL error : https://pkg-provides.osorio.me/v3/FreeBSD/14:amd64/provides.db.xz

$ openssl s_client -connect osorio.me:443 2>/dev/null | openssl x509 -text -noout | grep Not\ After
            Not After : Aug 23 18:13:12 2024 GMT
$ date
Sat Aug 24 07:02:04 UTC 2024

$ drill -Q pkg-provides.osorio.me
5.135.180.33
$ openssl s_client -connect pkg-provides.osorio.me:443
002081CE61470000:error:8000003D:system library:BIO_connect:Connection refused:/usr/src/crypto/openssl/crypto/bio/bio_sock2.c:125:calling connect()
002081CE61470000:error:10000067:BIO routines:BIO_connect:connect error:/usr/src/crypto/openssl/crypto/bio/bio_sock2.c:127:
connect:errno=61
```

I guess really the non-listening IP is really the root cause, but if all your certs are renewing on the same cron then the second one is going to rear its head too.

**Comment by jbirch** [comment]
This was fixed sometime in the last week. Thank you!

**Comment by rosorio** [comment]
Yes sorry for the inconvenience, I spend some time last week to update the pkg-provides serve. Thanks for the heads up and your patience.
