### ISSUE TITLE
FreeBSD 12 current fork Trident Beta 3: Doesn't work after installation

### ISSUE THREAD

**Issue by robertwolter** [rosorio/pkg-provides#2]
I have downloaded and installed pkg-provides but it doesn't work.

I had to manually create the following directories:

# mkdir -p /var/db/pkg/plugins
# mkdir -p /usr/local/etc/pkg/plugins
# mkdir /usr/local/lib/pkg

and made the installation:
# make install
install  -s -o root -g wheel -m 444   -S  provides.so /usr/local/lib/pkg/
install  -o root -g wheel -m 444    provides.so.debug /usr/local/lib/pkg/.debug/

I added to /usr/local/etc/pkg.conf:
PKG_PLUGINS_DIR = "/usr/local/lib/pkg/";
PKG_ENABLE_PLUGINS = true;
PLUGINS [ provides ];
PLUGINS_CONF_DIR = "/usr/local/etc/pkg/plugins";

But it doesn't work:
#  pkg provides -u
pkg: unknown command: provides

For more information on available commands and options see 'pkg help'.

**Comment by rosorio** [comment]
Hi Robert,
Firsts, thanks for the feedback.
I didn't perform manual installs since pkg-provides was i the ports and didn't check if the commands was properly updated since the first versions. I'll take a look on it tomorrow, but in the meantime, may I suggest you to install it from packages using the magic command  `pkg install pkg-provides` ?

Let me know if you still having issues with it, and as I said I will update the wiki tomorrow.
All the best,
- rodrigo

**Comment by robertwolter** [comment]
I have tried that as well, but no success.

```
pkg install pkg-provides
Updating TrueOS-ports repository catalogue...
TrueOS-ports repository is up to date.
Updating TrueOS-base repository catalogue...
TrueOS-base repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	pkg-provides: 0.5.0 [TrueOS-ports]

Number of packages to be installed: 1
[1/1] Installing pkg-provides-0.5.0...
[1/1] Extracting pkg-provides-0.5.0: 100%
Message from pkg-provides-0.5.0:

======================= pkg plugin activation ========================
  In order to use the pkg-provides plugin you need to enable plugins in pkg.
  To do this, uncomment the following lines in /usr/local/etc/pkg.conf file
  and add pkg-provides to the supported plugin list

  PKG_PLUGINS_DIR = "/usr/local/lib/pkg/";
  PKG_ENABLE_PLUGINS = true;
  PLUGINS [ provides ];

  After that run `pkg plugins' to see the plugins handled by pkg`.

  To update the provides database run `pkg provides -u`

  ====================================================================

```
ls -la /usr/local/lib/pkg/
total 571
drwxr-xr-x   2 root  wheel      3  4 Okt. 17:42 .
drwxr-xr-x  92 root  wheel   2390  4 Okt. 17:42 ..
-rw-r--r--   1 root  wheel  27240 23 Sep. 20:30 provides.so

I added to /usr/local/etc/pkg.conf:
PKG_PLUGINS_DIR = "/usr/local/lib/pkg/";
PKG_ENABLE_PLUGINS = true;
PLUGINS [ provides ];

And tried to update:
pkg provides -u
pkg: unknown command: provides

For more information on available commands and options see 'pkg help'.

**Comment by rosorio** [comment]
So, you are using TrueOS, nice;
The configuration looks fine, except I have no ';' at the end end of the PLUGINS line.
Did you try the pkg plugin to see at leas if the plugin was detected ?

I didn't took a look so I gonna try in the next days TrueOS wit pkg-plugins to see if something is missing.

Thanks again for your feedback, I know how frustrating this kind of issues can be, but it helps me a lot to improve the tool and ensure it will works smoothly in the future for everyone.

**Comment by robertwolter** [comment]
Yes, I tried that but it shows no plugin at all:
pkg plugins
NAME       DESC                                          VERSION   

I also removed the ";" in the PLUGINS line but that didn't change anything.

**Comment by robertwolter** [comment]
And I forgot to mention: It's not TrueOS 18.3 but Trident Beta 3 that I'm using. I just corrected this in the title.

**Comment by rosorio** [comment]
After taking a look it seems like that the trueos distributions uses a (modified ?) non vanilla freebsd pkg tool. If you type 'pkg upgrade' the tool warns you about what has to be done for trueos.

This doesn't mean I gonna close the ticket but this issue requires more investigations on the way trueos works.

Cheers.

**Comment by rosorio** [comment]
This issue is not solvable since trident distribution seems to pack their own pkg version
